graph TD
    A["<b>x402 Protocol</b><br/>Same HTTP · Same headers<br/>Same SDK · Same code"] --> B["<b>nvm:erc4337</b><br/>On-chain credits<br/>ERC-1155 on Base<br/>Crypto wallets<br/>Instant settlement"]
    A --> C["<b>nvm:card-delegation</b><br/>Stripe credit card<br/>Auto-recharge<br/>USD payments<br/>Familiar to users"]
